name: Get RSS Hourly

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_DB_RSS: ${{ secrets.NOTION_DB_RSS }}
      NOTION_DB_READER: ${{ secrets.NOTION_DB_READER }}
      MOONSHOT_API_KEY: ${{ secrets.MOONSHOT_API_KEY }}

    steps:
      - uses: actions/checkout@v4  # 更新到最新支持Node.js 20的版本
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4  # 更新到最新支持Node.js 20的版本
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v4  # 更新到最新支持Node.js 20的版本
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Load RSS feeds
        run: |
          python main.py
